### ISSUE TITLE
SDMX changes

### ISSUE THREAD

**Issue by davidread** [UKGovLD/publishing-statistical-data#1]
Received by data.gov.uk from Danny.Delcambre@ec.europa.eu:

> Hello,
> 
> I am contacting you on behalf of the SDMX group (http://sdmx.org) to inform
> you about broken links on the following page:
> https://raw.githubusercontent.com/UKGovLD/publishing-statistical-data/master/specs/src/main/vocab/sdmx-metadata.ttl
> 
> This is due to the recent migration of the sdmx.org website which triggered a
> change in the naming system of our files. As a consequence, of this, link:
> http://sdmx.org/wp-content/uploads/2009/01/01_sdmx_cog_annex_1_cdc_2009.pdf
> should be changed into:
> https://sdmx.org/wp-content/uploads/01_sdmx_cog_annex_1_cdc_2009.pdf
> 
> Sorry for the inconvenience.
> 
> Best regards,
> Danny DELCAMBRE

**Comment by der** [comment]
Done (affected most of the vocabs, not just the metadata one)
