### ISSUE TITLE
Duplicate triples in the Data Cube Vocabulary

### ISSUE THREAD

**Issue by jindrichmynarz** [UKGovLD/publishing-statistical-data#2]
There are duplicate triples in the Turtle serialization of the Data Cube Vocabulary (see [here](https://github.com/UKGovLD/publishing-statistical-data/blob/master/specs/src/main/vocab/cube.ttl#L201-L202)):

```
qb:ComponentSpecification rdfs:subClassOf qb:ComponentSet .
qb:SliceKey               rdfs:subClassOf qb:ComponentSet .
```

[Line 201](https://github.com/UKGovLD/publishing-statistical-data/blob/master/specs/src/main/vocab/cube.ttl#L201) duplicates [line 192](https://github.com/UKGovLD/publishing-statistical-data/blob/master/specs/src/main/vocab/cube.ttl#L192), while [line 202](https://github.com/UKGovLD/publishing-statistical-data/blob/master/specs/src/main/vocab/cube.ttl#L202) duplicates [line 274](https://github.com/UKGovLD/publishing-statistical-data/blob/master/specs/src/main/vocab/cube.ttl#L274).

This is a very minor issue. However, the duplication makes naïve size checks (such as counting the lines of N-Triples produced by Apache Jena Riot) to fail.

**Comment by der** [comment]
Thanks, harmless but fixed.

[Though the github raw view hasn't updated yet, presumably they do some caching.]
