### ISSUE TITLE
License for the SDMX vocabularies?

### ISSUE THREAD

**Issue by Ostrzyciel** [UKGovLD/publishing-statistical-data#5]
What is the license for the Turtle files here? https://github.com/UKGovLD/publishing-statistical-data/tree/master/specs/src/main/vocab

Without any clearly specified license, this defaults to "all rights reserved", which is pretty restrictive and (I think) probably not reflective of the original intent of the authors.

**Comment by csarven** [comment]
IANAL, and I do not have any authority on this repo or its contents.

That aside, some of the files include the PDDL: https://opendatacommons.org/licenses/pddl/1-0/ , and some of that work was carried out at W3C. You shouldn't have major barriers to put the URIs and its contents to use AFAICT but perhaps others can correct me.

**Comment by der** [comment]
Good question. The vocab files (other than sdmx.ttl itself, which has been superseded by the final Data Cube Rec) are derived directly from the SMDX COG files which are licensed under CC BY-SA 4.0 and so retain that license. 

I've added a LICENSE.md file in that directory to state that, let me know if you see any problems with the way I've done that.

**Comment by Ostrzyciel** [comment]
That's perfect, thank you!
